// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;
using RagHub.Infrastructure.Persistence;

#nullable disable

namespace RagHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RagDbContext))]
    [Migration("20260616134008_AddMultiQuerySettings")]
    partial class AddMultiQuerySettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RagHub.Core.Domain.Chunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharEnd")
                        .HasColumnType("integer")
                        .HasColumnName("char_end");

                    b.Property<int>("CharStart")
                        .HasColumnType("integer")
                        .HasColumnName("char_start");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<NpgsqlTsVector>("ContentTsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("content_tsv")
                        .HasComputedColumnSql("to_tsvector('english', content)", true);

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<int?>("EmbeddingDim")
                        .HasColumnType("integer")
                        .HasColumnName("embedding_dim");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<string>("HeadingPath")
                        .HasColumnType("text")
                        .HasColumnName("heading_path");

                    b.Property<int?>("PageNo")
                        .HasColumnType("integer")
                        .HasColumnName("page_no");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id")
                        .HasName("pk_chunks");

                    b.HasIndex("ContentTsv")
                        .HasDatabaseName("ix_chunks_content_tsv");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ContentTsv"), "GIN");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_chunks_document_id");

                    b.ToTable("chunks", (string)null);
                });

            modelBuilder.Entity("RagHub.Core.Domain.ChunkingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MaxChunkSize")
                        .HasColumnType("integer")
                        .HasColumnName("max_chunk_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Overlap")
                        .HasColumnType("integer")
                        .HasColumnName("overlap");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy");

                    b.HasKey("Id")
                        .HasName("pk_chunking_profiles");

                    b.ToTable("chunking_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxChunkSize = 1500,
                            Name = "Default",
                            Overlap = 100,
                            Strategy = "auto"
                        });
                });

            modelBuilder.Entity("RagHub.Core.Domain.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_count");

                    b.Property<int?>("ChunkSizeUsed")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_size_used");

                    b.Property<int?>("ChunkingProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("chunking_profile_id");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<int?>("EmbeddingDim")
                        .HasColumnType("integer")
                        .HasColumnName("embedding_dim");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("OverlapUsed")
                        .HasColumnType("integer")
                        .HasColumnName("overlap_used");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("ChunkingProfileId")
                        .HasDatabaseName("ix_documents_chunking_profile_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("RagHub.Core.Domain.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualAnswer")
                        .HasColumnType("text")
                        .HasColumnName("actual_answer");

                    b.PrimitiveCollection<List<int>>("ActualChunkIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("actual_chunk_ids");

                    b.Property<bool?>("CitationPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("citation_passed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpectedAnswer")
                        .HasColumnType("text")
                        .HasColumnName("expected_answer");

                    b.PrimitiveCollection<List<int>>("ExpectedChunkIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("expected_chunk_ids");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<double?>("ReciprocalRank")
                        .HasColumnType("double precision")
                        .HasColumnName("reciprocal_rank");

                    b.Property<bool?>("RetrievalPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("retrieval_passed");

                    b.Property<DateTime?>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.HasKey("Id")
                        .HasName("pk_evaluations");

                    b.ToTable("evaluations", (string)null);
                });

            modelBuilder.Entity("RagHub.Core.Domain.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rating");

                    b.PrimitiveCollection<List<int>>("RetrievedChunkIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("retrieved_chunk_ids");

                    b.HasKey("Id")
                        .HasName("pk_feedbacks");

                    b.ToTable("feedbacks", (string)null);
                });

            modelBuilder.Entity("RagHub.Core.Domain.RetrievalConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateK")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_k");

                    b.Property<int>("FinalN")
                        .HasColumnType("integer")
                        .HasColumnName("final_n");

                    b.Property<int>("MultiQueryCount")
                        .HasColumnType("integer")
                        .HasColumnName("multi_query_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseHybrid")
                        .HasColumnType("boolean")
                        .HasColumnName("use_hybrid");

                    b.Property<bool>("UseMultiQuery")
                        .HasColumnType("boolean")
                        .HasColumnName("use_multi_query");

                    b.Property<bool>("UseReranker")
                        .HasColumnType("boolean")
                        .HasColumnName("use_reranker");

                    b.HasKey("Id")
                        .HasName("pk_retrieval_configs");

                    b.ToTable("retrieval_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidateK = 20,
                            FinalN = 5,
                            MultiQueryCount = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UseHybrid = true,
                            UseMultiQuery = false,
                            UseReranker = true
                        });
                });

            modelBuilder.Entity("RagHub.Core.Domain.Chunk", b =>
                {
                    b.HasOne("RagHub.Core.Domain.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chunks_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RagHub.Core.Domain.Document", b =>
                {
                    b.HasOne("RagHub.Core.Domain.ChunkingProfile", "ChunkingProfile")
                        .WithMany()
                        .HasForeignKey("ChunkingProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_chunking_profiles_chunking_profile_id");

                    b.Navigation("ChunkingProfile");
                });

            modelBuilder.Entity("RagHub.Core.Domain.Document", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
